Pandas is a python library used for:

-reading data(csv,excel,etc)
-cleaning data
-analyzing data
-preparing data for visualisation

In [2]:
import pandas as pd

In [ ]:
#series vs dataframe

#a series is like a single column of data
#it is one dimensional

In [3]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
#custom index

s=pd.Series([85,90,88],index=["Asha","Ravi","Kiran"])
print(s)

Asha     85
Ravi     90
Kiran    88
dtype: int64

In [3]:
#Dataframe
#a dataframe is a table (rows+columns)
#it is 2-dimensional

data={
    "Name":["Asha","Ravi","Kiran"],
    "Marks":[85,98,67]
}
df=pd.DataFrame(data)
print(df)

print(df.index)
print(df.columns)
print(df.values)

    Name  Marks
0   Asha     85
1   Ravi     98
2  Kiran     67
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks'], dtype='str')
[['Asha' 85]
 ['Ravi' 98]
 ['Kiran' 67]]

In [4]:
#Data loading(ingestion)
#this is to bring data into pandas

df=pd.read_csv("North America Restaurants.csv")
df.head()   #first 5 rows

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30

In [6]:
df.head(10)
df.tail()   #last 5 rows

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1495,Grandma's Soul Food,Richmond,VA,23234,US,"American, Burgers, Chicken, Dessert, Dinner, K...",True,True,2.0,5
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1498,Denny's,Kingman,AZ,86401,US,"American, Breakfast And Brunch, Coffee And Tea...",True,True,3.4,22
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [ ]:
df.info()   #information of the file imported

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   name                     1500 non-null   str
 1   city                     1500 non-null   str
 2   state                    1500 non-null   str
 3   zipcode                  1500 non-null   str
 4   country                  1500 non-null   str
 5   cuisines                 1499 non-null   str
 6   pickup_enabled           1500 non-null   bool
 7   delivery_enabled         1500 non-null   bool
 8   weighted_rating_value    1500 non-null   float64
 9   aggregated_rating_count  1500 non-null   int64
dtypes: bool(2), float64(1), int64(1), str(6)
memory usage: 96.8 KB

In [ ]:
df.describe() #statistical information/summary of numeric columns

       weighted_rating_value  aggregated_rating_count
count            1500.000000              1500.000000
mean                3.724533                85.500667
std                 0.989005               277.071136
min                 1.000000                 1.000000
25%                 2.900000                 5.000000
50%                 4.100000                25.000000
75%                 4.600000                68.000000
max                 5.000000              4211.000000

In [ ]:
#load excel

df=pd.read_excel("Car Dashboard Source.xlsx",sheet_name="Budget")
df.head()

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.